-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Clientes"
(
id_cliente VARCHAR PRIMARY KEY,
senha_cliente VARCHAR,
nome_cliente VARCHAR(60),
telefone_cliente VARCHAR(15),
email_cliente VARCHAR(250),
cep_cliente VARCHAR(8)
veiculo VARCHAR(7) FOREIGN KEY,
endereco_cliente VARCHAR(60),
num_endereco VARCHAR(7),
complemento VARCHAR(30),
bairro VARCHAR(30),
cidade VARCHAR(30),
uf VARCHAR(2)
)
;

CREATE TABLE IF NOT EXISTS public."Funcionarios"
(
id_funcionario VARCHAR PRIMARY KEY,
senha_funcionario VARCHAR,
nome_funcionario VARCHAR(60) UNIQUE,
telefone_funcionario VARCHAR(15),
funcao VARCHAR,
rg_funcionario(9) UNIQUE,
cpf_funcionario VARCHAR(11) UNIQUE,
cep_funcionario VARCHAR(8),
endereco_funcionario VARCHAR(60),
num_endereco VARCHAR(7),
complemento VARCHAR(30),
bairro VARCHAR(30),
cidade VARCHAR(30),
uf VARCHAR(2)
)
;

CREATE TABLE IF NOT EXISTS public.tenant_oficina
(
)
;

CREATE TABLE IF NOT EXISTS public.veiculos
(
placa_veiculo VARCHAR(7) PRIMARY KEY,
chassi VARCHAR(17) UNIQUE,
marca VARCHAR(20),
modelo VARCHAR(20),
ano SMALLINT,
cor VARCHAR(20),
nome_cliente FOREIGN KEY,
codigo_cliente FOREIGN KEY,

ADD CONSTRAINT
FOREIGN KEY (nome_cliente)
REFERENCES clientes(nome_cliente),

ADD CONSTRAINT
FOREIGN KEY (codigo_cliente)
REFERENCES clientes(codigo_cliente)
)
;

CREATE TABLE IF NOT EXISTS public.pedidos
(
id_pedido VARCHAR PRIMARY KEY,
descricao_pedido TEXT,
data_pedido DATE,
)
;

CREATE TABLE IF NOT EXISTS public.orcamentos
(
id_orcamento VARCHAR PRIMARY KEY,
servico_est VARCHAR,
materiais_est
prazo_est
custo_est
)
;

CREATE TABLE IF NOT EXISTS public.ordens_servico
(
id_ordemservico VARCHAR PRIMARY KEY,
servicos VARCHAR,
materiais ,
prazo ,
custo ,
veiculo TEXT,
placa_veiculo VARCHAR(7),
nome_cliente FOREIGN KEY,
codigo_cliente FOREIGN KEY,

ADD CONSTRAINT
FOREIGN KEY (placa_veiculo)
REFERENCES veiculos(placa_veiculo),

ADD CONSTRAINT
FOREIGN KEY (nome_cliente)
REFERENCES clientes(nome_cliente),

ADD CONSTRAINT
FOREIGN KEY (codigo_cliente)
REFERENCES clientes(codigo_cliente)
)
;
END;